"""
NIDS/engine/runtime_state.py

Dual-state runtime storage for ShadowSCAN.

Architecture
------------
BaseRuntimeState          — shared interface and memory-capped list storage
  ├── LiveRuntimeState    — ONLY receives real pipeline data; update() is fully
  │                         implemented; pipeline_loop always writes here
  └── DemoRuntimeState    — update() is a sealed no-op firewall; live packets
                            NEVER enter this object under any circumstances

StateManager              — owns both states; gates all reads by current mode;
                            exposes a clean API so endpoints never touch raw
                            state objects directly

Module-level exports
--------------------
state_manager             — the singleton StateManager; import everywhere
state                     — backward-compat alias → state_manager.live_state
                            pipeline_loop calls state.update(result) which
                            always writes to LiveRuntimeState only

Isolation guarantee
-------------------
The pipeline runs continuously regardless of mode.  It always writes to
live_state.  When the dashboard is in Demo Mode the endpoints call
StateManager.get_X() which routes reads to DemoProvider, NEVER to
live_state.  When in Live Mode, reads go to live_state only — DemoProvider
is never touched.  On every mode switch, StateManager.on_mode_switch()
clears BOTH stores atomically so no residual data survives.
"""

import threading
from collections import deque
from Core.config.config_loader import load_detection_config


# ---------------------------------------------------------------------------
# BaseRuntimeState — shared interface
# ---------------------------------------------------------------------------

class BaseRuntimeState:
    """
    Common storage and memory-management for both Live and Demo states.

    Stores four independent lists:
        alerts   — security alert dicts generated by the detection engine
        flows    — network flow dicts from FlowBuilder
        sessions — session dicts from SessionBuilder
        packets  — raw parsed packet dicts from the capture reader

    All list mutations are protected by a reentrant lock so concurrent
    pipeline writes and API reads never race.
    """

    def __init__(self):
        self._lock = threading.RLock()

        _cfg = load_detection_config()
        self.max_items: int = _cfg.get("max_runtime_items", 200)

        self.alerts = deque(maxlen=self.max_items)
        self.flows = deque(maxlen=self.max_items)
        self.sessions = deque(maxlen=self.max_items)
        self.packets = deque(maxlen=self.max_items)

    # ------------------------------------------------------------------
    # update() — each subclass decides whether to accept pipeline data
    # ------------------------------------------------------------------

    def update(self, result: dict) -> None:
        """
        Ingest a pipeline result dict.

        Called by pipeline_loop on every sweep.
        Subclasses implement this to either accept or reject the data.
        """
        raise NotImplementedError(
            f"{self.__class__.__name__} must implement update()"
        )

    # ------------------------------------------------------------------
    # clear() — wipe all stored data (called on every mode switch)
    # ------------------------------------------------------------------

    def clear(self) -> None:
        """Remove all stored data from every list."""
        with self._lock:
            self.alerts.clear()
            self.flows.clear()
            self.sessions.clear()
            self.packets.clear()

    # ------------------------------------------------------------------
    # snapshot() — read-safe stats dict
    # ------------------------------------------------------------------

    def snapshot(self) -> dict:
        """Return current list lengths as a stats dict."""
        with self._lock:
            return {
                "packets":    len(self.packets),
                "flows":      len(self.flows),
                "sessions":   len(self.sessions),
                "alerts":     len(self.alerts),
                "alerts_24h": len(self.alerts),
            }


# LiveRuntimeState — receives ONLY real pipeline data
# ---------------------------------------------------------------------------

class LiveRuntimeState(BaseRuntimeState):
    """
    The authoritative store for all real network telemetry.

    Rules
    -----
    - update() is the ONLY write path; it is called exclusively by
      pipeline_loop in main.py.
    - Performs alert deduplication so the same flow does not generate
      duplicate entries across consecutive sweeps.
    - Memory-caps all four lists on every update.
    - Demo data is NEVER written here; DemoProvider never calls update().
    - Endpoints read from this object ONLY when mode == "live".
    """

    def update(self, result: dict) -> None:
        """
        Ingest a real pipeline result.  Thread-safe.
        Deduplicates alerts by (src_ip, dst_ip, attack_type) key.
        """
        with self._lock:
            # ── Alert deduplication ──────────────────────────────────────
            existing_keys = {
                (a.get("src_ip"), a.get("dst_ip"), a.get("attack_type"))
                for a in self.alerts
            }

            for alert in result.get("alerts", []):
                key = (
                    alert.get("src_ip"),
                    alert.get("dst_ip"),
                    alert.get("attack_type"),
                )
                if key not in existing_keys:
                    self.alerts.append(alert)
                    existing_keys.add(key)

            # ── Flows, sessions, packets ─────────────────────────────────
            self.flows.extend(result.get("flows", []))
            self.sessions.extend(result.get("sessions", []))
            self.packets.extend(result.get("packets", []))

    def get_alerts(self, limit: int = 100) -> list:
        """Return the last `limit` live alerts as a shallow copy."""
        with self._lock:
            return list(self.alerts)[-limit:]

    def get_flows(self) -> list:
        """Return all stored live flows as a shallow copy."""
        with self._lock:
            return list(self.flows)

    def get_sessions(self) -> list:
        """Return all stored live sessions as a shallow copy."""
        with self._lock:
            return list(self.sessions)


# ---------------------------------------------------------------------------
# DemoRuntimeState — firewall against live data
# ---------------------------------------------------------------------------

class DemoRuntimeState(BaseRuntimeState):
    """
    A sealed, isolated state store that NEVER accepts pipeline data.

    Rules
    -----
    - update() is a deliberate, permanent no-op.  It is the primary
      firewall preventing real packets, flows, sessions, and alerts from
      ever appearing in demo mode.
    - This class holds no data of its own.  Demo data is always generated
      on-demand by DemoProvider and returned directly to endpoints.
    - clear() works normally for hygiene on mode switches.
    - The class exists as a typed, lockable container so StateManager can
      treat both states uniformly while guaranteeing isolation.

    Why a class rather than just returning early in endpoints?
    ----------------------------------------------------------
    A named class makes the isolation contract explicit, auditable, and
    enforceable at the type level.  Any future code path that accidentally
    calls DemoRuntimeState.update() will silently discard the data rather
    than leaking it, making the system fault-tolerant by design.
    """

    def update(self, result: dict) -> None:
        """
        PERMANENT NO-OP.  This is the isolation firewall.

        Live pipeline data is discarded here and NEVER stored.
        This method will never contain any logic that writes data.
        """
        # Intentionally empty — discard all pipeline results.
        pass


# ---------------------------------------------------------------------------
# StateManager — single gatekeeper for all state reads and writes
# ---------------------------------------------------------------------------

class StateManager:
    """
    Owns both a LiveRuntimeState and a DemoRuntimeState.
    Routes all data reads to the correct store based on current mode.
    Pipeline writes always go to live_state, regardless of mode.

    Public API (used by endpoints in main.py)
    -----------------------------------------
    state_manager.is_demo()          → bool
    state_manager.get_alerts()       → list  (demo or live, with geo enrichment hook)
    state_manager.get_flows()        → list
    state_manager.get_sessions()     → list
    state_manager.get_stats()        → dict
    state_manager.get_live_alerts()  → list  (raw, live only; for enrichment in endpoint)
    state_manager.on_mode_switch()   → None  (clears both states atomically)

    Pipeline write path (used by pipeline_loop in main.py)
    -------------------------------------------------------
    state.update(result)             → writes to live_state ONLY
    """

    def __init__(self):
        #: Receives all real pipeline data; always writable by pipeline_loop.
        self.live_state = LiveRuntimeState()

        #: Permanently sealed against pipeline data.
        self.demo_state = DemoRuntimeState()

    # ------------------------------------------------------------------
    # Mode query
    # ------------------------------------------------------------------

    def is_demo(self) -> bool:
        """
        Return True if the system is currently in Demo Mode.
        Imported lazily to avoid circular imports at module load time.
        """
        from Core.mode_manager import mode_manager
        return mode_manager.current_mode == "demo"

    # ------------------------------------------------------------------
    # Mode-aware data accessors
    # ------------------------------------------------------------------

    def get_flows(self) -> list:
        """
        Return flows for the current mode.
          Demo → DemoProvider (replay flows; never real packets)
          Live → LiveRuntimeState (captured flows only)
        """
        if self.is_demo():
            from Core.demo_provider import demo_provider
            return demo_provider.get_flows()
        return self.live_state.get_flows()

    def get_sessions(self) -> list:
        """
        Return sessions for the current mode.
          Demo → DemoProvider (replay sessions; never real sessions)
          Live → LiveRuntimeState (pipeline sessions only)
        """
        if self.is_demo():
            from Core.demo_provider import demo_provider
            return demo_provider.get_sessions()
        return self.live_state.get_sessions()

    def get_stats(self) -> dict:
        """
        Return overview statistics for the current mode.
          Demo → DemoProvider (evolving realistic numbers)
          Live → Core.metrics (real pipeline packet/flow/alert counts)
        """
        if self.is_demo():
            from Core.demo_provider import demo_provider
            return demo_provider.get_stats()
        from Core.metrics import snapshot
        return snapshot()

    def get_live_alerts(self, limit: int = 100) -> list:
        """
        Return raw live alerts for geo-enrichment in the /alerts endpoint.

        ONLY call this when mode == "live".  The /alerts endpoint checks
        is_demo() first and calls DemoProvider instead if needed.
        This method always reads from live_state — never from demo_state.
        """
        return self.live_state.get_alerts(limit=limit)

    # ------------------------------------------------------------------
    # Mode switch hook
    # ------------------------------------------------------------------

    def on_mode_switch(self) -> None:
        """
        Called by ModeManager every time the operating mode changes.

        Clears BOTH state stores atomically so no residual data from the
        previous mode can appear in the new mode.

        After a switch:
          - live_state will immediately start refilling from the pipeline.
          - demo_state is always filled on demand by DemoProvider.
          - Core metrics counters are reset to zero.
        """
        self.live_state.clear()
        self.demo_state.clear()

        try:
            from Core.metrics import set_counts
            set_counts(packets=0, flows=0, sessions=0, alerts=0)
        except Exception:
            pass


# ---------------------------------------------------------------------------
# Module-level singletons
# ---------------------------------------------------------------------------

#: The central state manager.  Import `state_manager` everywhere.
state_manager = StateManager()

#: Backward-compatible alias so that the existing pipeline_loop code
#: `state.update(result)` continues to work without modification.
#: Always points to state_manager.live_state — pipeline writes go to
#: LiveRuntimeState only, regardless of the current mode.
state = state_manager.live_state